### ISSUE TITLE
Design Contribution Proposal

### ISSUE THREAD

**Issue by ihtiht** [stoyicker/dinger#282]
Hi, @stoyicker 

I am a graphic designer. I support open source projects by making designs. I am here because I like this project. I designed a logo for Dinger. I hope you like it.

![dingerview](https://user-images.githubusercontent.com/36369736/42420425-579a28c8-82ce-11e8-9f63-7246e0b5eb7b.jpg)

![view12](https://user-images.githubusercontent.com/36369736/42420448-c85bfa96-82ce-11e8-9043-519876080fa1.jpg)

![view](https://user-images.githubusercontent.com/36369736/42420513-873a0368-82cf-11e8-8973-6ece2de75e2e.jpg)

If you like, I can send it by opening a PR. Tell me if there is something you want to change or add. 

I will be waiting for your feedback ..

**Comment by stoyicker** [comment]
Hey,

thanks for passing by! It's cool to see people interested in the project.
It looks really cool actually, definitely also makes a bit more sense that the current icon. If you can prepare replacement for the launcher icons and the splash screen I'd be open to replace them.
Just a small piece of feedback: I kind of like the current font on the website over the one that there is on your new logo. Would it be possible to merge the flame-y thing with the current header font?

**Comment by ihtiht** [comment]
After shaping the design as you like, I will send the necessary files by opening a PR. I tried to do what you want about the font. I did not know the name of the font used in the website, so I used a similar font. If you say the name of the font we can get better results. 
Comparison of old and new ;
![currentfont](https://user-images.githubusercontent.com/36369736/42424016-cbdc67d0-830c-11e8-9cea-7baa1c91aaca.PNG)

**Comment by stoyicker** [comment]
This should be all info about the font: https://ibb.co/b1hSRo

**Comment by ihtiht** [comment]
I applied the font you requested.

![dingerroboto](https://user-images.githubusercontent.com/36369736/42477757-11540b5a-83db-11e8-95e3-1d08e00c2904.jpg)

**Comment by stoyicker** [comment]
Thanks for the test! I know I may be a bit picky, but it doesn't look like the d and the rest of the word merge too well (since they're using different fonts I guess?).
Would it be possible to make the d use roboto as well, and then perhaps thin out the flame a little bit to accommodate the change smoothly?

**Comment by ihtiht** [comment]
The letter d was not made with a font. I designed it by drawing. Because I thought it should draw attention. With the classic letter d, the design will not look good. I did what I wanted and I synced the letter d with the font. The new look is as follows.

![gorunum](https://user-images.githubusercontent.com/36369736/42599303-7a1f46c6-8567-11e8-933d-ff100496aaf0.jpg)

You may want to use this version in your website. But the old design as a mobile application icon gets better. Because, as mobile icons are smaller in size, more saturated designs are needed.

![1](https://user-images.githubusercontent.com/36369736/42599419-d46f76b4-8567-11e8-8d75-cb243f3df8d6.jpg)


I look forward to your feedback ..

**Comment by stoyicker** [comment]
In that case, I think I prefer to leave the banner as it is, having the handdrawn letter next to the others doesn't really blend in well I think.
Regarding the logo:

* it definitely makes more sense that the current 'dot-in-a-dot' one, but if we get rid of the d for the website, there's no reason to have it on the logo. Could we ditch it and just keep the flame?
* for all I've seen this type of Android app logos don't normally have this gradient in the background, but instead a solid color and a sideways shadow, see the Google Duo or Allo apps as examples. Perhaps we should do the same here - the accent color for the app should be #FFECB3 in case it helps.

Keep it up!

**Comment by ihtiht** [comment]
Do you want it to be just a flame? Did I get right? If this is what you want, the new design will look like this.  The 1st design color code is # FFECB3. 

![colors](https://user-images.githubusercontent.com/36369736/42709557-978a9f84-86e9-11e8-9085-952888779b73.jpg)

**Comment by stoyicker** [comment]
Neat. I'd say take the first one, apply #263238 to the flame instead of white so that it fits the current theme colors and just go straight for the pull request - we've already iterated quite a bit. 

Good job, looking forward to your PR!

**Comment by ihtiht** [comment]
I sent a Pull Request containing all the necessary files. https://github.com/stoyicker/dinger/pull/284 Please let me know if something is missing.

**Comment by stoyicker** [comment]
Closing as I'm considering the discussion moved to the PR(s)
