### ISSUE TITLE
Dockerize CI

### ISSUE THREAD

**Issue by stoyicker** [stoyicker/dinger#57]
1. Build and upload the new image to the Docker Hub if the Dockerfile is in the diff between HEAD@branch and master.
2. Use the Docker image in Travis instead of installing everything.

**Comment by muralov** [comment]
I would like to contribute to dockerize this. Can you please help me how I can contribute?

**Comment by muralov** [comment]
I would like to contribute to dockerize this. Can you please help me how I can contribute?

**Comment by stoyicker** [comment]
Hey, thanks for that!

Apologies that I haven't added contribution guidelines quite yet, I'll try to do it later today.
Just fork the repo and put up a PR against master with your patch when it's ready.

**Comment by EleanorRigby** [comment]
@stoyicker : The thing that you want to do is basically, run travis commands(testing and uploading of release etc..) in a Docker environment rather than local. Is it?
I thought Travis does that for you automatically.

**Comment by stoyicker** [comment]
The gain/way I want to use Docker in is saving the time that takes to download and, specially, install all the android tools that are required. If you take a look at a build the actual command in script takes way less than the actual build time, the culprit being the time required to install the android components.
If I can have an image in DockerHub that has everything installed already I can skip the:
`android:
  components:
  - tools
  - platform-tools
  - android-26
  - build-tools-26.0.2
  - extra-android-m2repository
  - extra-google-m2repository`

block. For that I'd have a dockerfile defining the image and, after it gets modified, it would need to be rebuilt and reuploaded as a before_install or something so the one that gets downloaded for that build is the correct one (as one could assume that the fact that the dockerfile is modified would imply that some change somewhere else in the repo, like a newer version of some build tool, is the cause of the dockerfile diff).

**Comment by muralov** [comment]
Hi stoyicker,

can you help me to resolve one issue related to android SDK? The issues is the following when I run the gradle build:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Platform 26, Android SDK Build-Tools 26.0.2].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

Thanks,
Mansur

**Comment by stoyicker** [comment]
@muralov can you post the commands you're using to set up the environment? Or the Dockerfile, if you're with that already.

**Comment by muralov** [comment]
@stoyicker I was trying to run Gradle build with "gradle build" locally first. I am not running the command in Dockerfile yet.

**Comment by stoyicker** [comment]
If you're getting that when trying to run locally you most certainly didn't install the exact version of the build tools (or, if you did, they're not in the right directory because they're not being used).
Does the output of `sdkmanager --list` include `build-tools;26.0.2` under Installed Packages (should be somewhere near the start of the output)? If it doesn't, try to run `sdkmanager "build-tools;26.0.2"`. If it does, please post your `$ANDROID_HOME`.

**Comment by muralov** [comment]
@stoyicker thank your tip. Now when I run "gradle build" I receive the following error in the console:

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /home/mansur/Dev/open-source/dinger/app/src/debug/google-services.json
  /home/mansur/Dev/open-source/dinger/app/google-services.json

**Comment by stoyicker** [comment]
The project uses Firebase for event tracking and crash reporting. google-services.json is one of the files you need to configure it, but those files are not under version control because they contain information that is sensitive to my personal accounts. You would need to set up a project in the Firebase console of your own, and then get the configuration files from there and place them in the project. However, you really don't need to do that. If you can write an image such as running the command inside an instance of it takes you to this error, then you're done and can submit a PR with it. I'll download the image from your PR and test it with my Firebase files so you don't have to just to make sure, but it's unlikely anything else will be needed as all the android tools required should be evaluated before the presence of Firebase files.
