### ISSUE TITLE
gh-page

### ISSUE THREAD

**Issue by stoyicker** [stoyicker/dinger#59]
Hard requirements:
- [x] Page should be mobile friendly.
- [x] favicon
- [x] Remove GA
- [x] Introduction with subsection about tracked info.
- [x] Download (QR code to the latest release should be shown). Also version number of current release.
- [x] Architecture.
- [x] https://developers.google.com/web/updates/2014/11/Support-for-theme-color-in-Chrome-39-for-Android
- [x] Contributing.
- [x] License.

External links:
- [x] API documentation.

**Comment by isuruAb** [comment]
hello @stoyicker  what did you mean by "README should be shown." do you need to show the content of the README file in gh-pages preview ?

**Comment by stoyicker** [comment]
I think it'd be nice if we can show it from master, yes. Would it be too much of a hassle?
